// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBusManagement.Repositories;

#nullable disable

namespace MiniBusManagement.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230609052627_Roles")]
    partial class Roles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.CompanyDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertionDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "359 Avon",
                            City = "San Jose",
                            ContactName = "Roberto Diaz",
                            ContactNumber = "2655666",
                            Email = "Roberto@gmail.com",
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1362),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1435),
                            Name = "Prueba",
                            Phone = "25655656",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM"
                        },
                        new
                        {
                            Id = 2,
                            Address = "359 chch",
                            City = "San Jose",
                            ContactName = "Roberto Perez",
                            ContactNumber = "250000",
                            Email = "Roberto@hotmail.com",
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1438),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1440),
                            Name = "Prueba",
                            Phone = "25655656",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM"
                        });
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.MiniBusDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Minibuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Capacity = 3,
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1648),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1650),
                            Plate = "PAK715",
                            Tipo = "Van",
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mazada",
                            Capacity = 6,
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1687),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1689),
                            Plate = "CL1715",
                            Tipo = "Car",
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Isuzu",
                            Capacity = 7,
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1691),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1692),
                            Plate = "BUS715",
                            Tipo = "Bus",
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Ford",
                            Capacity = 8,
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1694),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1696),
                            Plate = "625630",
                            Tipo = "Tri",
                            Year = 0
                        });
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.RolDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rol 01 de Gerentes de tiendas",
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1623),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1625),
                            Name = "Gerentes",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Rol 02 de Gerentes de ferreterias",
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1628),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1629),
                            Name = "Gerentes Ferrteria",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM"
                        });
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.UserDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1599),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1601),
                            UserEmail = "prueba01@gmail.com",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM",
                            UserName = "Usuario 01",
                            UserPassword = "pass01",
                            UserPhone = "25365600",
                            login = "Rdiaz"
                        },
                        new
                        {
                            Id = 2,
                            InsertionDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1604),
                            ModificationDate = new DateTime(2023, 6, 9, 17, 26, 27, 111, DateTimeKind.Local).AddTicks(1606),
                            UserEmail = "prueba02@gmail.com",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM",
                            UserName = "Usuario 02",
                            UserPassword = "pass02",
                            UserPhone = "25365600",
                            login = "Rdiaz02"
                        });
                });

            modelBuilder.Entity("RolDBEntityUserDBEntity", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RolDBEntityUserDBEntity");
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.MiniBusDBEntity", b =>
                {
                    b.HasOne("MiniBusManagement.Repositories.Entities.Administration.CompanyDBEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.RolDBEntity", b =>
                {
                    b.HasOne("MiniBusManagement.Repositories.Entities.Administration.CompanyDBEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.UserDBEntity", b =>
                {
                    b.HasOne("MiniBusManagement.Repositories.Entities.Administration.CompanyDBEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RolDBEntityUserDBEntity", b =>
                {
                    b.HasOne("MiniBusManagement.Repositories.Entities.Administration.RolDBEntity", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniBusManagement.Repositories.Entities.Administration.UserDBEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
