// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBusManagement.Repositories;

#nullable disable

namespace MiniBusManagement.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230608000501_company")]
    partial class company
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.CompanyDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertionDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "359 Avon",
                            City = "San Jose",
                            ContactName = "Roberto Diaz",
                            ContactNumber = "2655666",
                            Email = "Roberto@gmail.com",
                            InsertionDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9070),
                            ModificationDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9123),
                            Name = "Prueba",
                            Phone = "25655656",
                            UserInsert = "Roberto",
                            UserModifies = "RobertoM"
                        });
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.MiniBusDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Minibuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Capacity = 3,
                            CompanyId = 1,
                            InsertionDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9231),
                            ModificationDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9233),
                            Plate = "PAK715",
                            Tipo = "Van",
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mazada",
                            Capacity = 6,
                            CompanyId = 1,
                            InsertionDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9235),
                            ModificationDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9236),
                            Plate = "CL1715",
                            Tipo = "Car",
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Isuzu",
                            Capacity = 7,
                            CompanyId = 1,
                            InsertionDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9238),
                            ModificationDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9239),
                            Plate = "BUS715",
                            Tipo = "Bus",
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Ford",
                            Capacity = 8,
                            CompanyId = 1,
                            InsertionDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9276),
                            ModificationDate = new DateTime(2023, 6, 8, 12, 5, 1, 186, DateTimeKind.Local).AddTicks(9278),
                            Plate = "625630",
                            Tipo = "Tri",
                            Year = 0
                        });
                });

            modelBuilder.Entity("MiniBusManagement.Repositories.Entities.Administration.MiniBusDBEntity", b =>
                {
                    b.HasOne("MiniBusManagement.Repositories.Entities.Administration.CompanyDBEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
