// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBusManagement.Repository.Data;

#nullable disable

namespace MiniBusManagement.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230601232935_Minibus01")]
    partial class Minibus01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniBusManagement.Repository.Administration.MiniBusDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Minibuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Capacity = "3",
                            IdCompany = 1,
                            InsertionDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3679),
                            ModificationDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3739),
                            Tipo = "Van",
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mazada",
                            Capacity = "6",
                            IdCompany = 1,
                            InsertionDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3742),
                            ModificationDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3743),
                            Tipo = "Car",
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Isuzu",
                            Capacity = "7",
                            IdCompany = 1,
                            InsertionDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3745),
                            ModificationDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3746),
                            Tipo = "Bus",
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Ford",
                            Capacity = "8",
                            IdCompany = 1,
                            InsertionDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3748),
                            ModificationDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3749),
                            Tipo = "Tri",
                            Year = 0
                        });
                });

            modelBuilder.Entity("MiniBusManagement.Repository.Administration.PlaceDBEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserInsert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifies")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Canton = "Puriscal",
                            InsertionDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3863),
                            ModificationDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3865),
                            Name = "Ruta Herradura",
                            Provincia = "San José",
                            UserInsert = "Roberto Diaz",
                            UserModifies = "Roberto"
                        },
                        new
                        {
                            Id = 2,
                            Canton = "Ciudad Colón",
                            InsertionDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3868),
                            ModificationDate = new DateTime(2023, 6, 2, 11, 29, 35, 805, DateTimeKind.Local).AddTicks(3870),
                            Name = "Ruta del Sol",
                            Provincia = "San José",
                            UserInsert = "Roberto Diaz",
                            UserModifies = "Roberto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
